config/routes.rb
Rails.application.routes.draw do
  get 'place_photos/create'
  devise_for :users
  root to: 'pages#home'

  get 'about', to: 'pages#about'

  get 'profile/:id', to: 'users#show', as: :profile
  get 'profile/:id/dogs', to: 'dogs#index'
  post 'profile/:id/dogs', to: 'dogs#create',as: :user_dogs
  get 'profile/:id/dogs/new', to: 'dogs#new', as: :new_user_dog
  get 'profile/dogs/:id/edit', to: 'dogs#edit', as: :edit_user_dog
  patch 'profile/dogs/:id', to: 'dogs#update', as: :update_user_dog

  delete 'profile/dogs/:id', to: 'dogs#destroy', as: :destroy_dogs
  # post 'profile/:id/favorites', to: 'favorites#create', as: :new_favorite
  # post 'activity_review/', to: 'activity_reviews#create', as: :new_activity_review


  resources :activities do
    resources :payments, only: [:new, :create]
    resources :activity_reviews, only: [:create]
    resources :activity_photos, only: [:create]
    resources :favorites, only: [:destroy, :create]
  end

  resources :orders, only: [:index, :create, :destroy]

  resources :places do
    resources :place_reviews, only: [:create]
    resources :place_photos, only: [:create]
    resources :favorites, only: [:create, :destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/dog.rb
class Dog < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  belongs_to :user
  validates :my_story, length: { minimum: 20 }
  validates :name, presence: true
  validates :breed, presence: true
  validates :user_id, presence: true
  validates :dog_size, presence: true, inclusion: { in: ['Toy - up to 12 pounds', 'Small - 12 to 25 pounds', 'Medium - 25 to 50 pounds', 'Large - 50 to 100 pounds', 'Extra Large - over 100 pounds'] }
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]

  def index
    @dogs = policy_scope(Dog).order(name: :asc)
  end

  def new
    @dog = Dog.new
    @user = current_user
    @dog.user = @user
    @dog_size = ['Toy - up to 12 pounds', 'Small - 12 to 25 pounds', 'Medium - 25 to 50 pounds', 'Large - 50 to 100 pounds', 'Extra Large - over 100 pounds']
    authorize @dog
  end

  def create
    @dog = Dog.new(dog_params)
    @user = current_user
    @dog.user = @user
    authorize @dog
    if @dog.save
      redirect_to profile_path(@user)
    else
      render :new
    end
  end

  def destroy
    @dog = Dog.find(params[:id])
    authorize @dog
    if @dog.destroy
      redirect_to profile_path(current_user)
    else
      render :new
    end
  end

  def edit
    @dog_size = ['1. Lowest pet-friendliness', '2. Below average pet-friendliness', '3. Average pet-friendliness', '4. Exceptional pet-friendliness', '5. Dogs have near-human status']
    @dog = Dog.find(params[:id])
    @dog_size = ['Toy - up to 12 pounds', 'Small - 12 to 25 pounds', 'Medium - 25 to 50 pounds', 'Large - 50 to 100 pounds', 'Extra Large - over 100 pounds']
    @user = current_user
    authorize @dog
    # raise
  end

  def update
    @dog = Dog.find(params[:id])
    @dog.update(dog_params)
    authorize @dog
    if @dog.save
      redirect_to profile_path(current_user)
    else
      render :edit
    end
  end

  private

  def dog_params
    params.require(:dog).permit(:photo, :name, :my_story, :breed, :dog_size)
  end
end

app/views/dogs/edit.html.erb
<div class="container mb-5">
  <div class="row center">
    <div class="form-event">
      <%= simple_form_for @dog, url: update_user_dog_path(@dog) do |f| %>
        <%= f.input :name,
                    required: true %>
        <%= f.input :my_story,
                    required: true %>
        <%= f.input :dog_size, required: true, collection: @dog_size %>
        <%= f.input :breed %>
        <%= f.input :photo %>
        <%= f.input :photo_cache, as: :hidden %>
        <div class="form-actions">
          <%= f.button :submit, "Update dog" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/dogs/index.html.erb
<%= link_to "Add a dog", user_dogs_path(current_user) %>
<% @dogs.each do |dog| %>
  <ul class="list-group">
    <li class="list-group">
      <%= dog.name %>
    </li>
  </ul>
<% end %>

app/views/dogs/new.html.erb
<div class="container mb-5">
  <div class="row center">
    <div class="form-event">
      <h2>Add Your Dog</h2>
      <%= simple_form_for [@user, @dog] do |f| %>
        <%= f.input :name,
                    required: true %>
        <%= f.input :my_story,
                    required: true %>
        <%= f.input :breed,
                    required: true %>
        <%= f.input :dog_size, collection: @dog_size %>
        <%= f.input :photo %>
        <%= f.input :photo_cache, as: :hidden %>
        <div class="form-actions">
          <%= f.button :submit, "Add doggo" %>
        </div>
      <% end %>
    </div>
  </div>
</div>