config/routes.rb
Rails.application.routes.draw do
  get 'place_photos/create'
  devise_for :users
  root to: 'pages#home'

  get 'about', to: 'pages#about'

  get 'profile/:id', to: 'users#show', as: :profile
  get 'profile/:id/dogs', to: 'dogs#index'
  post 'profile/:id/dogs', to: 'dogs#create',as: :user_dogs
  get 'profile/:id/dogs/new', to: 'dogs#new', as: :new_user_dog
  get 'profile/dogs/:id/edit', to: 'dogs#edit', as: :edit_user_dog
  patch 'profile/dogs/:id', to: 'dogs#update', as: :update_user_dog

  delete 'profile/dogs/:id', to: 'dogs#destroy', as: :destroy_dogs
  # post 'profile/:id/favorites', to: 'favorites#create', as: :new_favorite
  # post 'activity_review/', to: 'activity_reviews#create', as: :new_activity_review


  resources :activities do
    resources :payments, only: [:new, :create]
    resources :activity_reviews, only: [:create]
    resources :activity_photos, only: [:create]
    resources :favorites, only: [:destroy, :create]
  end

  resources :orders, only: [:index, :create, :destroy]

  resources :places do
    resources :place_reviews, only: [:create]
    resources :place_photos, only: [:create]
    resources :favorites, only: [:create, :destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :login

  mount_uploader :avatar, AvatarUploader

  has_many :dogs, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :activity_reviews, dependent: :destroy
  has_many :place_reviews, dependent: :destroy
  has_many :places, dependent: :destroy
  has_many :activities, class_name: 'Activity', foreign_key: :owner_id
  has_many :orders

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :username, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true
  validates :bio, length: { minimum: 10 }
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    login = conditions.delete(:login)
    where(conditions).where(["lower(username) = :value OR lower(email) = :value", {value: login.strip.downcase}]).first
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show]

  def show
    @user = User.find(params[:id])
    authorize @user
  end
end

app/views/users/show.html.erb
<div class="profile">
  <div class="profile-banner d-flex">
    <div class="user-name">
      <% if @user.username.present? %>
        <h1><%= @user.username %></h1>
      <% else %>
        <h1>Username</h1>
      <% end %>
    </div>
  </div>
</div>

<div class="profile-container">
  <div class="container">
    <div class="profile-main d-flex">

      <div class="user-info d-flex justify-content-between">

        <div class="profile-pic">
          <% if @user.avatar.present? %>
            <%= cl_image_tag @user.avatar, alt: @user.username, class: "avatar-large" %>
          <% else %>
            <%= image_tag "http://diazworld.com/images/avatar-placeholder.png", alt: "avatar-placeholder", width: 200, height: 200 %>
          <% end %>
        </div>

        <div class="contact-me">
          <h4>Contact</h4>
          <% if @user.email.present? %>
            <p>e-mail: <%= @user.email %></p>
          <% else %>
            <p>No contact details yet</p>
          <% end %>
        </div>

        <div class="about-me">
          <h4>About me</h4>
          <% if @user.bio.present? %>
            <p><%= @user.bio %></p>
          <% else %>
            <p><%= user.name %> has no bio yet</p>
          <% end %>
        </div>
        <div class="acc-settings">
          <%= link_to "Account credentials", edit_user_registration_path, class: 'user-btn' %>

          <%= link_to "Delete account", user_registration_path, method: :delete, data: { confirm: 'Are you sure?' }, class: 'user-btn' %>
        </div>

      </div>

      <div class="user-addition">
        <div class="user-dogs">
          <h2 class="meet-friend">Meet my best friend
            <%= link_to "+", new_user_dog_path %></h2>
          <div class="all-user-dogs d-flex justify-content-around">
            <% @user.dogs.each do |dog| %>
              <div class="each-dog">
                <div class="dog-avatar">
                  <% if dog.photo.present? %>
                    <%= cl_image_tag dog.photo, alt: dog.name, width: 250, height: 250, crop: :fill %>
                  <% else %>
                    <%= image_tag "https://meredith.nhcrafts.org/wp-content/uploads/dog-placeholder.jpg", alt: "dog-placeholder", width: 250, height: 250 %>
                  <% end %>
                </div>
                <div class="dog-description">
                  <h5><strong><%= dog.name %></strong></h5>
                  <p><%= dog.my_story %></p>
                  <p>Breed: <%= dog.breed %></p>
                  <p>Dog Size: <%= dog.dog_size %></p>

                  <div class="dog-settings">
                     <%= link_to edit_user_dog_path(dog) do %><i class="fas fa-pencil-alt"></i><% end %>
                     <%= link_to destroy_dogs_path(dog), method: :delete, data: { confirm: 'Are you sure?' } do %><i class="far fa-trash-alt"></i><% end %>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>

        <div class="user-favorites">
          <h2>Favorites</h2>
            <% if @user.favorites.present? %>
              <div class="favorite-user-activity d-flex">
                <% @user.favorites.each do |favorite| %>
                  <%= link_to activity_path(favorite.activity) do %>
                    <div class="favorite-card d-flex">
                      <%= cl_image_tag favorite.activity.activity_photos.first.photo, width: 271, height: 165, crop: :fill %>
                      <p ><strong><%= favorite.activity.name %></strong></p>
                    </div>
                  <% end %>
                <% end %>
              </div>
            <% else %>
              <p class="text-center">No favorite places or events added yet</p>
            <% end %>
        </div>
      </div>

    </div>
  </div>
</div>