config/routes.rb
Rails.application.routes.draw do
  get 'place_photos/create'
  devise_for :users
  root to: 'pages#home'

  get 'about', to: 'pages#about'

  get 'profile/:id', to: 'users#show', as: :profile
  get 'profile/:id/dogs', to: 'dogs#index'
  post 'profile/:id/dogs', to: 'dogs#create',as: :user_dogs
  get 'profile/:id/dogs/new', to: 'dogs#new', as: :new_user_dog
  get 'profile/dogs/:id/edit', to: 'dogs#edit', as: :edit_user_dog
  patch 'profile/dogs/:id', to: 'dogs#update', as: :update_user_dog

  delete 'profile/dogs/:id', to: 'dogs#destroy', as: :destroy_dogs
  # post 'profile/:id/favorites', to: 'favorites#create', as: :new_favorite
  # post 'activity_review/', to: 'activity_reviews#create', as: :new_activity_review


  resources :activities do
    resources :payments, only: [:new, :create]
    resources :activity_reviews, only: [:create]
    resources :activity_photos, only: [:create]
    resources :favorites, only: [:destroy, :create]
  end

  resources :orders, only: [:index, :create, :destroy]

  resources :places do
    resources :place_reviews, only: [:create]
    resources :place_photos, only: [:create]
    resources :favorites, only: [:create, :destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="container">
    <nav class="row">
      <section class="col-sm-12 col-md-6 col-lg-3">
        <h3 class="fancy">Company Info</h3>
          <ul class="footer-buttons" style="padding: 0;">
            <li>
              <a href="/about">About Retrievr</a>
            </li>
            <li>
              <a href="#">Promotions</a>
            </li>
            <li>
              <a href="#">Tell a friend!</a>
            </li>
            <li>
              <a href="#">We are hiring!</a>
            </li>
          </ul>
      </section>
      <section class="col-sm-12 col-md-6 col-lg-3">
        <h3 class="fancy">Partners</h3>
          <ul class="footer-buttons" style="padding: 0;">
            <li>
              <a href="#">Advertise with us</a>
            </li>
            <li>
              <a href="#">Media</a>
            </li>
            <li>
              <a href="#">Pet Charities</a>
            </li>
          </ul>
      </section>
      <section class="col-sm-12 col-md-6 col-lg-3">
        <h3 class="fancy">Customer Services</h3>
          <ul class="footer-buttons" style="padding: 0;">
            <li>
              <a href="#">Contact us</a>
            </li>
            <li>
              <a href="#">Cancel Orders</a>
            </li>
            <li>
              <a href="#">FAQ</a>
            </li>
          </ul>
      </section>
         <section class="col-sm-12 col-md-6 col-lg-3">
          <h3 class="fancy">Talk to Us!</h3>
          <p>Need help finding a pet friendly hotel, restaurant, or animal attraction? Contact our Canine Concierge at:</p>
          <span><a href="tel:+628-777-888">+628-777-888</a>
          <p style="display: inline">&nbsp;or</p>
          <a href="mailto:hello@retrievr.com">hello@retrievr.com</a></span>
          <div class="footer-links">
            <a href="#"><i class="fab fa-instagram"></i></a>
            <a href="#"><i class="fab fa-facebook"></i></a>
            <a href="#"><i class="fab fa-twitter"></i></a>
            <a href="#"><i class="fab fa-linkedin"></i></a>
            <h5> #retrievr</h5>
          </div>
      </section>
    </nav>

    <hr>
    <div class="footer-copyright">
      <a href="#">© 2019 Retrievr</a>
      <a href="/privacy/">Privacy Policy</a>
      <a href="/terms/">Terms &amp; Conditions</a>
      <a href="/sitemap/">Sitemap</a>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <!-- <a class="navbar-brand" href="#">Retrievr</a> -->
  <%= link_to root_path do %>
    <%= image_tag "retrievr_logo.png", alt: "retrievr-logo", class: 'logo' %>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto main-links">
      <li class="nav-item">
        <%= link_to "THINGS TO DO", activities_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to "PLACES TO GO", places_path, class: 'nav-link'  %>
      </li>
    </ul>

    <ul class="navbar-nav mr-0 text-center">
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <% if current_user.avatar.present? %>
            <%= cl_image_tag current_user.avatar, class: 'avatar dropdown-toggle', crop: :fill, id: 'navbarDropdown', data: { toggle: 'dropdown' }, aria: { haspopup: true, expanded: false } %>
          <% else %>
            <%= image_tag "https://png.pngtree.com/svg/20161027/631929649c.svg", alt: "avatar", class: 'avatar dropdown-toggle', id: 'navbarDropdown', data: { toggle: 'dropdown' }, aria: { haspopup: true, expanded: false } %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Orders", href="/orders", class: "dropdown-item" %>
            <%= link_to "View profile", profile_path(current_user), class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item non-login">
          <%= link_to "LOGIN", new_user_session_path, class: "secondary-links login-link" %>
        </li>
        <li class="nav-item non-login"><br></li>
        <li class="nav-item non-login">
          <%= link_to "SIGN UP", new_user_registration_path, class: 'btn-su'  %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>