config/routes.rb
Rails.application.routes.draw do
  get 'place_photos/create'
  devise_for :users
  root to: 'pages#home'

  get 'about', to: 'pages#about'

  get 'profile/:id', to: 'users#show', as: :profile
  get 'profile/:id/dogs', to: 'dogs#index'
  post 'profile/:id/dogs', to: 'dogs#create',as: :user_dogs
  get 'profile/:id/dogs/new', to: 'dogs#new', as: :new_user_dog
  get 'profile/dogs/:id/edit', to: 'dogs#edit', as: :edit_user_dog
  patch 'profile/dogs/:id', to: 'dogs#update', as: :update_user_dog

  delete 'profile/dogs/:id', to: 'dogs#destroy', as: :destroy_dogs
  # post 'profile/:id/favorites', to: 'favorites#create', as: :new_favorite
  # post 'activity_review/', to: 'activity_reviews#create', as: :new_activity_review


  resources :activities do
    resources :payments, only: [:new, :create]
    resources :activity_reviews, only: [:create]
    resources :activity_photos, only: [:create]
    resources :favorites, only: [:destroy, :create]
  end

  resources :orders, only: [:index, :create, :destroy]

  resources :places do
    resources :place_reviews, only: [:create]
    resources :place_photos, only: [:create]
    resources :favorites, only: [:create, :destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :owner, class_name: 'User', foreign_key: :owner_id
  belongs_to :place, optional: true
  has_many :activity_photos, dependent: :destroy
  has_many :activity_reviews, dependent: :destroy
  has_many :guests
  has_many :users, through: :guests
  has_many :favorites

  monetize :price_cents

  accepts_nested_attributes_for :activity_photos

  validates :price, presence: true
  validates :name, presence: true
  validates :address, presence: true
  validates :description, presence: true, length: { minimum: 20 }
  # validates :date, presence: true
  validates :category, presence: true
  validates :limit, presence: true
  validates :dog_size, presence: true, inclusion: { in: ['Toy - up to 12 pounds', 'Small - 12 to 25 pounds', 'Medium - 25 to 50 pounds', 'Large - 50 to 100 pounds', 'Extra Large - over 100 pounds'] }
  # validate :not_blank_date

  private

  def not_blank_date
    if !time.nil?
      errors.add(:time, "Can't be in the past") if time < DateTime.now
    end
  end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :user, only: [:create]
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @favorite = Favorite.new
    @params = params

    respond_to do |format|
      format.html do
        @activities = Activity.all
        render :index
      end

      format.js do
        if params[:price].present?
          @activities = Activity.order(price_cents: params[:price])
        elsif params[:category].present?
          @activities = Activity.where(category: params[:category])
        elsif params[:dog_size].present?
          @activities = Activity.where(dog_size: params[:dog_size])
        else
          @activities = Activity.all
        end
      end
    end
    @categories = @activities.all.map {|a| a.category}.uniq
  end

  def show
    @user = current_user
    @activity = Activity.find(params[:id])
    authorize @activity
    @activity_review = ActivityReview.new
  end

  def new
    @activity = Activity.new
    @activity_photos = @activity.activity_photos.build
    @dog_size = ['Toy - up to 12 pounds', 'Small - 12 to 25 pounds', 'Medium - 25 to 50 pounds', 'Large - 50 to 100 pounds', 'Extra Large - over 100 pounds']
    authorize @activity
  end

  def create
    @activity = Activity.new(activity_params)
    @activity.owner = @user
    # @place = Place.find(params[:activity][:place])
    # @activity.place = @place
    authorize @activity

    if @activity.save
      params[:activity][:photo].each do |p|
        @activity_photo = @activity.activity_photos.create!(photo: p, activity_id: @activity.id)
      end
      redirect_to activity_path(@activity)
    else
      render :new
    end
  end

  def edit
    @activity = Activity.find(params[:id])
    authorize @activity
  end

  def update
    @activity = Activity.find(params[:id])
    @activity.update(activity_params)
    authorize @activity
  end

  def destroy
    @activity = Activity.find(params[:id])
    authorize @activity

    if @activity.destroy
      redirect_to activities_path
    else
      render :index
    end
  end

  private

  def user
    @user = current_user
  end

  def activity_params
    params.require(:activity).permit(:name, :price, :description, :category, :date, :address, :limit, :dog_size, activity_photos_attributes: [:id, :photo])
  end
end

app/views/activities/_cards.html.erb
<div class="row results">
  <% @activities.each do |activity| %>
    <div class="col-sm-12 col-md-6 col-lg-6 mb-5">
      <%= link_to activity_path(activity), class: 'activity-link' do %>
        <div class="card-trip card-act" data-activity-id="<%= activity.id %>">
          <% if activity.activity_photos.present? %>
            <%= cl_image_tag activity.activity_photos.sample.photo, crop: :fill %>
          <% end %>
          <div class="card-trip-infos">
            <h5><%= activity.name %></h5>
            <p class="activity-time"><%= activity.time.to_s.gsub(' UTC', '') %></p>
            <% if activity.price == 0 %>
              <p class="activity-price">FREE</p>
            <% else %>
              <p class="activity-price"><%= humanized_money_with_symbol(activity.price) %>
              </p>
            <% end %>
          </div>
          <% if current_user %>
            <div class="card-favorite">
            <% if Favorite.find_by(activity: activity, user: current_user) %>
              <%= render 'favorites/delete', activity: activity %>
            <% else %>
              <%= render 'favorites/create', activity: activity %>
            <% end %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/activities/_filter.html.erb
<div class="filter-dropdown">
  <div class="dropdown-content dropdown-hide" id="dropdownFilter">
    <div class="dropdown-container">
      <div class="price-filter mb-2">
        <p id="category"><strong>Price</strong></p>
        <div class="price-params">
          <%= link_to 'Price DESC', activities_path(price: 'DESC'), remote: true %>
        </div>
      </div>

      <div class="category-filter">
        <p id="category"><strong>Category</strong></p>
        <ul class="category">
          <% @activities.all.map { |a| a.category }.uniq.each do |cat| %>
            <li>
              <%= link_to cat, activities_path(category: cat), remote: true %>
            </li>
          <% end %>
        </ul>
      </div>
      <div class="time-filter">
        <p id="category"><strong>Dog Size</strong></p>
        <ul class="category">
          <% @activities.all.map { |a| a.dog_size }.uniq.each do |size| %>
            <li>
              <%= link_to size, activities_path(dog_size: size), remote: true %>
              </li>
          <% end %>
        </ul>
      </div>
      <div class="reset-filter">
        <p id="category"><strong>Reset filter</strong></p>
        <%= link_to 'Reset', activities_path, remote: true %>
      </div>
    </div>
  </div>
</div>

app/views/activities/_form.html.erb
<div class="container mb-5">
  <div class="row center">
    <div class="form-event">
      <br>
      <h2> Create New Event </h2>

      <%= simple_form_for @activity, html: { multipart: true, class: 'row' } do |f| %>
        <div class="col-sm-12 col-md-12 col-lg-12">
          <%= f.input :name %>
        </div>
        <div class="col-sm-12 col-md-12 col-lg-12">
          <%= f.input :description, placeholder: 'minimum: 20 characters' %>
        </div>
        <div class="col-sm-6 col-md-12 col-lg-12">
          <%= f.input :address %>
        </div>
        <div class="col-sm-6 col-md-12 col-lg-12">
          <%= f.input :time %>
        </div>
        <div class="col-sm-6 col-md-12 col-lg-12">
          <%= f.input :category, collection: ['Pool', 'Feast', 'Gathering', 'Party', 'Competition', 'Other'] %>
        </div>
        <div class="col-sm-6 col-md-12 col-lg-6">
          <%= f.input :price, placeholder: '$00.00' %>
        </div>
        <div class="col-sm-6 col-md-12 col-lg-6">
          <%= f.input :limit %>
        </div>
        <div class="col-sm-6 col-md-12 col-lg-12">
          <%= f.input :dog_size, collection: @dog_size %>
        </div>
        <div class="col-sm-6 col-md-12 col-lg-12 my-2" id="upload-btn-wrapper">
          <%= f.fields_for :activity_photos do |p| %>
        <label class="field">
              <%= f.file_field :photo, multiple: true %>
        </label>
        <% end %>
          <br>
        </div>

        <div class="col-sm-12 col-md-12 col-lg-12">
          <%= f.submit "Create Event", class: 'btn btn-login'  %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/activities/edit.html.erb
<div class="container">
  <div class="edit-activities">
    <%= render 'form' %>
  </div>
</div>

app/views/activities/index.html.erb
<div class="container">
  <h2 class="text-center my-3" style="color: #FF5959">Events</h2>

  <div class="sides">
    <%= render 'filter' %>
    <%= render 'cards' %>
  </div>
</div>

<div class="text-center">
  <%= link_to new_activity_path do %>
    <button type="button" class="user-btn"> Add New Event </button>
  <% end %>
</div>

app/views/activities/index.js.erb
function filter(activities) {
  const results = document.querySelector('.results');
  results.innerHTML = activities;
}

<% unless @params[:price].nil? || @params[:price].empty? %>
  var priceParams = document.querySelector('.price-params');

  <% if @params[:price] == 'DESC' %>
    priceParams.innerHTML = '<%= link_to "Price ASC", activities_path(price: "ASC"), remote: true %>';
  <% elsif @params[:price] == 'ASC' %>
    priceParams.innerHTML = '<%= link_to "Price DESC", activities_path(price: "DESC"), remote: true %>';
  <% end %>
<% end %>

filter('<%= j render "activities/cards", activities: @activities %>')

app/views/activities/new.html.erb
<%= render 'form' %>
    

app/views/activities/old_show.html.erb
<div class="activity-container">
  <div class="container">
    <div class="activity-about">
      <h1 style="color: orange; text-align: center; margin-bottom: 40px;"><%= @activity.name %></h1>
      <div class="about-content d-flex justify-content-around align-items-center flex-row">
        <div class="activity-grid">

          <div class="activity-details d-flex justify-content-between">
            <div class="">
              <div class="activity-details-category">
                <div class="w-100 d-flex justify-content-around"><p><strong>Date</strong></p>
                <p><strong>Price</strong></p>
                <p><strong>Location</strong></p>
                <p><strong>Category</strong></p>
                <p><strong>Dog size</strong></p>
                <p><strong>Creator</strong></p>
              </div>

              <div class="activity-details-input">
                <p><%= @activity.date %></p>
                <p><%= humanized_money_with_symbol(@activity.price) %></p>
                <p><%= @activity.place.name %></p>
                <p><%= @activity.category %></p>
                 <p><%= @dog_size %></p>
                <p><%= @activity.owner.first_name %> <%= @activity.owner.last_name %></p>
              </div>

              <div class="activity-details-btn col-md-6">
                <%= form_tag orders_path do %>
                <%= hidden_field_tag 'activity_id', @activity.id %>
                <%= submit_tag 'Place Order', data: { confirm:"Are you sure?" }, class: 'btn-activity' %>
                <% end %>
              </div>
            </div>

            <%= cl_image_tag @activity.activity_photos.first.photo, crop: :fill, width: 500, height: 300 %>
          </div>

        </div>
      </div>

      <div>
        <div class="activity-description">
          <p><%= @activity.description %></p>
        </div>

        <div class="activity-photos">
          <h2 style="color: orange">Photos</h2>
          <div class="act-photos">
            <% @activity.activity_photos.each do |p| %>
            <%= cl_image_tag p.photo, width: 300, height: 200, crop: :fill, g: :face, class: 'activity-photo' %>
            <% end %>
          </div>

          <div class="activity-photo-upload text-center">
            <ul class="list-inline" style="font-size: 18px; margin-top: 50px;">
              <li style="color: orange; font-weight: bold">Upload your picture now!</li>
            </ul>

            <ul class="list-group">
              <li class="list-group-item">
                <%= render 'activity_photos/formphotos' %>
              </li>
            </ul>
          </div>
        </div>

        <div class="activity-reviews">
          <h2 style="color: orange">Reviews</h2>
          <% @activity.activity_reviews.each do |r| %>
          <ul class="list-group">
            <li class="list-group-item review-content">
              <div class="review-image text-center">
                <% if r.user.avatar.present? %>
                <%= cl_image_tag r.user.avatar, crop: :fill, g: :face, class: 'avatar-huge' %>
                <% else %>
                <%= image_tag "http://diazworld.com/images/avatar-placeholder.png", alt: "avatar-placeholder", width: 120, height: 120 %>
                <% end %>
                <h6 style='margin-top: 8px; margin-bottom: 0'>@<%= r.user.username %></h6>
                <p style="color: gray; margin-bottom: 0;"><%= r.created_at %></p>
              </div>

              <div class="review-ratings">
                <div class="rating-bones">
                  <% r.rating.times do %>
                  <i class="fas fa-bone" style="color: orange; font-size: 24px; transform: rotate(-45deg);"></i>
                  <% end %>
                </div>

                <% if r.content.present? %>
                <div class="review-text">
                  <p><%= r.content %></p>
                </div>
                <% end %>
              </div>
            </li>
          </ul>
          <% end %>

          <% if @activity.owner != current_user %>
          <div class="review-form">
            <p id="new_review" class="text-center" style="color: orange; font-size: 20px; cursor: pointer">
              <i class="fas fa-pen">&nbsp;</i>Submit a review
            </p>

            <div class="activity-review-form hide-form">
              <%= render 'activity_reviews/form' %>
            </div>
          </div>
          <% end %>
        </div>
      </div>
      <%#= link_to "Back to list", activities_path, class: 'btn btn-warning' %>
    </div>
  </div>

app/views/activities/show.html.erb
<div class="container pt-5">
  <h1 style="color: #FF5959; text-align: center; margin-bottom: 40px;"><%= @activity.name.capitalize %></h1>

  <div class="row mt-5">
    <div class="col-md-5 px-5">
      <div class="activity-details">
        <div class="act-details">
          <div class="activity-details-category">
            <div><p><strong>Date:</strong></p><p class="text-right"> <%= @activity.time %></p></div>
            <div><p><strong>Price:</strong></p><p id="price" class="text-right"> <%= humanized_money_with_symbol(@activity.price) %></p></div>
            <div><p><strong>Location:</strong></p><p class="text-right"> <%= @activity.address %></p></div>
            <div><p><strong>Category:</strong></p><p class="text-right"> <%= @activity.category %></p></div>
             <div><p><strong>Dog Size:</strong></p><p class="text-right"><%= @activity.dog_size %></p></div>
            <div><p><strong>Creator:</strong></p><p class="text-right"> <%= @activity.owner.first_name %> <%= @activity.owner.last_name %></p></div>
            <br>
          </div>
          <div class="payment-act text-center">
            <h4>Get a ticket</h4>
            <%= render 'payments/pay' %>
          </div>
        </div>
      </div>

    </div>
    <div class="col-md-7">
      <%= cl_image_tag @activity.activity_photos[0].photo, crop: :fill, height: 350, class: "show-page-pic" %>
    </div>

  </div>
</div>

<div class="container">
  <div class="activity-description">
    <p><%= @activity.description %></p>
  </div>
</div>

<div class="background-photo">
  <div class="container pt-4">
    <h2 style="color: #FF5959; text-align: left; margin-bottom: 40px;">Photos</h2>

    <div class="row">
      <% @activity.activity_photos.each do |p| %>
      <div class="col-md-4 py-2">
        <div class="act-photos">
          <%= cl_image_tag p.photo, height: 200, crop: :fill, g: :face, class: 'activity-photo' %>
        </div>
      </div>
      <% end %>
    </div>

    <div class="activity-photo-upload text-center">
      <ul class="list-inline" style="font-size: 18px; margin-top: 50px;">
        <li style="color: #FF5959; font-weight: bold">Upload your picture now!</li>
      </ul>
      <ul class="list-group">
        <li class="list-group-item">
          <%= render 'activity_photos/formphotos' %>
        </li>
      </ul>
    </div>
  </div>
</div>

<div class="container">
  <div class="activity-reviews">
    <h2 style="color: #FF5959">Reviews</h2>
    <% @activity.activity_reviews.each do |r| %>
    <ul class="list-group">
      <li class="list-group-item review-content">
        <div class="review-image text-center">
          <% if r.user.avatar.present? %>
          <%= cl_image_tag r.user.avatar, crop: :fill, g: :face, class: 'avatar-huge' %>
          <% else %>
          <%= image_tag "http://diazworld.com/images/avatar-placeholder.png", alt: "avatar-placeholder", width: 120, height: 120 %>
          <% end %>
          <h6 style='margin-top: 8px; margin-bottom: 0'>@<%= r.user.username %></h6>
          <p style="color: gray; margin-bottom: 0;"><%= r.created_at %></p>
        </div>

        <div class="review-ratings">
          <div class="rating-bones">
            <% r.rating.times do %>
            <i class="fas fa-bone" style="color: #FF5959; font-size: 24px; transform: rotate(-45deg);"></i>
            <% end %>
          </div>

          <% if r.content.present? %>
          <div class="review-text">
            <p><%= r.content %></p>
          </div>
          <% end %>
        </div>
      </li>
    </ul>
    <hr>

    <% end %>

    <% if @activity.owner != current_user %>
    <div class="review-form">
      <p id="new_review" class="text-center" style="color: #FF5959; font-size: 20px; cursor: pointer">
        <i class="fas fa-pen">&nbsp;</i>Submit a review
      </p>

      <div class="activity-review-form hide-form">
        <%= render 'activity_reviews/form' %>
      </div>
    </div>
    <% end %>
  </div>
</div>